name: Demo Starter Workflow

# Workflow Trigger: This workflow runs on push and pull request events to the main branch
on:
  # Webhook events
  push:
    branches: 
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
    
# Jobs: Define a set of jobs to be run as part of the workflow
jobs:
  HelloWorld-job:
    # Specify the runner environment, choose from ubuntu, windows, macOS
    runs-on: ubuntu-latest
    
    steps:
      # Step: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step: Print Hello World
      - name: Print Hello World
        run: echo "Hello, World!"
        
      # Step: Print current date and time
      - name: Print Date and Time
        run: date
      
      # Step: Print GitHub context information. GitHub Context is a collection of environment variables that can be used in the workflow with the format ${{ github.<context> }} and contains default information about the repository, workflow, and run.
      - name: Print GitHub Context
        run: echo "This is a GitHub Actions workflow running on ${{ github.runner.os }} for the repository ${{ github.repository }}."
        
      # Step: Set an output variable using $GITHUB_ENV environment variable to be used in subsequent steps. Output variables are defined using the syntax ${{ steps.<step-id>.outputs.<output-name> }}. If you want to use the output in a different job, you can use the needs.<job-id>.outputs.<output-name> syntax instead which uses the $GITHUB_OUTPUT environment variable.
      - name: Set Output Variable
        id: set-output
        run: echo "myOutput=Hello from the workflow!" >> $GITHUB_ENV
      
      # Step: Use the output variable
      - name: Use Output Variable
        run: echo "The output variable is $myOutput"
  
  # You can use different runners like ubuntu, windows, macos for the same job
  Matrix-job:
        runs-on: ubuntu-latest
        needs: HelloWorld-job
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Print OS
          run: echo "The OS is ${{ matrix.os }}"

  # You can use different shells like bash, pwsh, python, cmd
  # docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell
  # pwsh (Powershell Core) is the default shell on Windows.
  # For Linux/macOS, the default shell is sh.

  Shell-job:
        runs-on: ubuntu-latest
        needs: HelloWorld-job

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Print using Bash
          run: echo "Hello from Bash"

        - name: Print using PowerShell (pwsh)
          run: Write-Output "Hello from PowerShell"
          shell: pwsh 

        - name: Print using Python
          run: |
            python -c "print('Hello from Python')"
            
  # You can reference GitHub Actions using SHA, Tag, or Branch
  reference-job:
            runs-on: ubuntu-latest
            steps:
            - run: echo "Hi from branch"
            - name: Checkout code
              uses: actions/checkout@main

            - run: echo "Hi from SHA"
            - name: Use action from SHA
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              # github.com/actions/checkout/commit/11bd71901bbe5b1630ceea73d27597364c9af683
            - run: echo "Hi from Tag"
            - name: Use action from Tag
              uses: actions/checkout@v4

