name: Hello World Workflow

# Workflow Trigger: This workflow runs on push and pull request events to the main branch
on:
  # Webhook events
  push:
    branches: 
      - main
  workflow_dispatch:
    # set run_matrix to 'true' to run the matrix job
    inputs:
      run_matrix:
        description: 'Run the matrix job'
        required: false
        default: 'false'
  pull_request:
    branches:
      - main
    
# Jobs: Define a set of jobs to be run as part of the workflow
jobs:
  hello-world-job:
    # Specify the runner environment
    runs-on: ubuntu-latest
    
    steps:
      # Step: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step: Print Hello World
      - name: Print Hello World
        run: echo "Hello, World!"
        
      # Step: Print current date and time
      - name: Print Date and Time
        run: date
      
      # Step: Print GitHub context information
      - name: Print GitHub Context
        run: echo "This is a GitHub Actions workflow running on ${{ github.runner.os }} for the repository ${{ github.repository }}."
        
      # Step: Set an output variable
      - name: Set Output Variable
        id: set-output
        run: echo "myOutput=Hello from the workflow!" >> $GITHUB_ENV
      
      # Step: Use the output variable
      - name: Use Output Variable
        run: echo "The output variable is $myOutput"
  
  # write a simple matrix job without errors
  matrix-job:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Print OS
          run: echo "The OS is ${{ matrix.os }}"